name: Hello World

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, Back-End Developers!"

      - name: Show Python version
        run: python --version

      - name: Show My Name
        run: echo "Winnie Kurgat"